#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(FOCUS_PUNCH) \
    F(DRAGON_CLAW) \
    F(WATER_PULSE) \
    F(CALM_MIND) \
    F(ROAR) \
    F(TOXIC) \
    F(HAIL) \
    F(BULK_UP) \
    F(BULLET_SEED) \
    F(HIDDEN_POWER) \
    F(SUNNY_DAY) \
    F(TAUNT) \
    F(ICE_BEAM) \
    F(BLIZZARD) \
    F(HYPER_BEAM) \
    F(LIGHT_SCREEN) \
    F(PROTECT) \
    F(RAIN_DANCE) \
    F(GIGA_DRAIN) \
    F(SAFEGUARD) \
    F(FRUSTRATION) \
    F(SOLAR_BEAM) \
    F(IRON_TAIL) \
    F(THUNDERBOLT) \
    F(THUNDER) \
    F(EARTHQUAKE) \
    F(RETURN) \
    F(DIG) \
    F(PSYCHIC) \
    F(SHADOW_BALL) \
    F(BRICK_BREAK) \
    F(DOUBLE_TEAM) \
    F(REFLECT) \
    F(SHOCK_WAVE) \
    F(FLAMETHROWER) \
    F(SLUDGE_BOMB) \
    F(SANDSTORM) \
    F(FIRE_BLAST) \
    F(ROCK_TOMB) \
    F(AERIAL_ACE) \
    F(TORMENT) \
    F(FACADE) \
    F(SECRET_POWER) \
    F(REST) \
    F(ATTRACT) \
    F(THIEF) \
    F(STEEL_WING) \
    F(SKILL_SWAP) \
    F(SNATCH) \
    F(OVERHEAT)\
    F(ROOST)\
    F(FOCUS_BLAST)\
    F(ENERGY_BALL)\
    F(ROCK_BLAST)\
    F(BRINE)\
    F(U_TURN)\
    F(CHARGE_BEAM)\
    F(ASSURANCE)\
    F(ZEN_HEADBUTT)\
    F(DRAIN_PUNCH)\
    F(SHADOW_CLAW)\
    F(ACROBATICS)\
    F(NASTY_PLOT)\
    F(AVALANCHE)\
    F(AIR_SLASH)\
    F(THUNDER_FANG)\
    F(ICE_FANG)\
    F(FIRE_FANG)\
    F(PSYCHO_CUT)\
    F(TRICK_ROOM)\
    F(SEED_BOMB)\
    F(ELECTRO_BALL)\
    F(CROSS_POISON)\
    F(VENOSHOCK)\
    F(STEALTH_ROCK)\
    F(BRAVE_BIRD)\
    F(HEX)\
    F(BULLDOZE)\
    F(RETALIATE)\
    F(VOLT_SWITCH)\
    F(GRASS_KNOT)\
    F(ELECTROWEB)\
    F(RAZOR_SHELL)\
    F(POISON_JAB)\
    F(SNARL)\
    F(PHANTOM_FORCE)\
    F(DRAINING_KISS)\
    F(GRASSY_TERRAIN)\
    F(MISTY_TERRAIN)\
    F(ELECTRIC_TERRAIN)\
    F(PSYCHIC_TERRAIN)\
    F(DAZZLING_GLEAM)\
    F(WILD_CHARGE)\
    F(CLOSE_COMBAT)\
    F(LEECH_LIFE)\
    F(SMART_STRIKE)\
    F(DARK_PULSE)\
    F(POWER_UP_PUNCH)\
    F(BODY_PRESS)

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
